POST http://localhost:8080/updatePassword
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJSb2xlIjoic2VydmlzZXIiLCJVc2VyX0lEIjoxMDAsIlVzZXJuYW1lIjoiTWlsYW4yMTIiLCJleHAiOjE3Mzk0MDQ3ODJ9.PavnCBlyh-0jSD-Cegbd2SS7FNTer_-Hj3-qx9cMksk

{     
	"new_password": "Milan333",
  "old_password": "Milan212"  
}