GET http://localhost:8080/izvjestaji/radni-nalog/23
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJSb2xlIjoiYWRtaW4iLCJVc2VyX0lEIjoxMywiVXNlcm5hbWUiOiJkYXZvciIsImV4cCI6MTczOTk5Mjg0N30.HKUAPsiP7QMiUBPfQDSAsYJXO_MOaDM8cAgHQ9swsmM