GET http://localhost:8080/radni-nalozi/arhiva/filter
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJSb2xlIjoiYWRtaW4iLCJVc2VyX0lEIjoxMywiVXNlcm5hbWUiOiJkYXZvciIsImV4cCI6MTczNzExOTg4NX0.0P09tnqS_N-awpoCMs9bJDIVDhfpkr5QgC4Rf5h28z4

{   
    "date_from": "2024-12-22T12:30:00Z",
    "status": "Zavrsen"
}
