PUT http://localhost:8080/radni-nalozi/22/zavrsi?Serviser_ID=101
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJSb2xlIjoiYWRtaW4iLCJVc2VyX0lEIjoxMywiVXNlcm5hbWUiOiJkYXZvciIsImV4cCI6MTczNTU1ODc5OX0.136G3lmEbFeGeIN9vl7B1V7N_s-s1e_H2b3xk1U_lmg