POST http://localhost:8080/fakture/generisi/24
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJSb2xlIjoiYWRtaW4iLCJVc2VyX0lEIjoxMywiVXNlcm5hbWUiOiJkYXZvciIsImV4cCI6MTczOTU0OTAxN30.SKHAu0R1RevCDbXJxeiwY0pkni4czuJvBeZgNbnEmBk